theme: jekyll-theme-minimal
title: Riccccardo's Home of Ideas, Projects, Thoughts, and Rantings
description: I'm a Desktop Support Tech in an undisclosed industry. I am in the process of further educating myself with knoeldge surrounding the Linux, RaspberryPI, and Web Development. I came across the feature of hosting your website on GitHub Pages, and am willing to give this a try!
